version: '3.8'

services:
  
  backend:
    image: beatrizrosaa/backend-app:v1.0.0  
    container_name: meu_backend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: finances
      POSTGRES_PORT: 5432
      POSTGRES_CREATE_DROP: update
      POSTGRES_HOST: database
      SECRET_KEY: "uma_chave_secreta_qualquer"
      JWT_EXPIRATION_TIME: 86400
      CORS_ALLOWED_ORIGINS: "*"
      SWAGGER_ENABLED: true
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: postgres:16.3
    container_name: meu_banco
    restart: always
    environment:
      POSTGRES_DB: finances
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data2

  frontend:
    image: beatrizrosaa/frontend-app:v1.0.0 
    container_name: meu_frontend
    environment:

      - REACT_APP_API_URL=http://localhost:8080  
    ports:
      - "4200:4200" 
    depends_on:
      - backend

volumes:
  pgdata: